name: perf-test

env:
  PULUMI_ACCESS_TOKEN: 'fake-as-only-using-local-state'

on:
  push:

jobs:
  perf-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.3'
      - run: yarn install
      - run: yarn exec pulumi login --local
      - run: yarn exec pulumi preview
